name: scikit-fem-dev
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - pytest
  - ipython
  - sphinx
  - pip
  - pip:
    - meshio
    - dmsh
    - pygmsh
    - scikit-sparse
    - pacopy
    - sphinx_rtd_theme
