on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run flake8, mypy and pytest on Python 3.7
        uses: kinnala/scikit-fem-docker-action@v5
