on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests inside a container
        uses: kinnala/scikit-fem-docker-action@v2
