on: [push, pull_request]

jobs:
  run_tests_37:
    runs-on: ubuntu-latest
    name: Run tests on Python 3.7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: kinnala/scikit-fem-docker-action@v6
